### PR TITLE
Fix issue no #96

### PR DESCRIPTION
**Pull request by RituCs**
Add footer for RocketMeet Client.
Screenshot from 2021-03-14 22-03-55

### CODE REVIEW

**Comment by AnandBaburajan** [comment]
Hey @RituCs! Thank you for your contribution! I've some suggestions - actually they're the same I mentioned at Gitter like those underlines and the footer width. PTAL, thanks! :D Also if you like, we can remove that octocat and just put Github in the follow us section. What do you think? You can remove the RocketMeet logo from the footer and just put a text.

**Comment by AnandBaburajan** [comment]
Fixes #96

**Comment by RituCs** [comment]
> Hey @RituCs! Thank you for your contribution! I've some suggestions - actually they're the same I mentioned at Gitter like those underlines and the footer width. PTAL, thanks! :D Also if you like, we can remove that octocat and just put Github in the follow us section. What do you think? You can remove the RocketMeet logo from the footer and just put a text.

Ok I will do what you have mentioned.I think it would be good if we remove the octocat and put Github link in follow us section.

**Comment by AnandBaburajan** [comment]
Thanks! Can you share a screenshot for our convenience? :D Also you need to fix the conflicts in `package.json`.

**Comment by RituCs** [comment]
> Thanks! Can you share a screenshot for our convenience? :D Also you need to fix the conflicts in `package.json`.

Yeah Sure.
Screenshot from 2021-03-22 22-03-05

**Comment by AnandBaburajan** [comment]
Looks better! Thank you! By the comments about 'floating' at Gitter, I meant something like this:
image
Also it would be nice if the links had some hover color changes.

**Comment by anaswaratrajan** [comment]
@RituCs Looks really good! Just what I had in mind. :D Thanks!

**Comment by RituCs** [comment]
> Looks better! Thank you! By the comments about 'floating' at Gitter, I meant something like this:
> image
> Also it would be nice if the links had some hover color changes

Is it ok??
Screenshot from 2021-03-27 00-22-05

**Comment by AnandBaburajan** [comment]
Perfect! Thanks!

**Comment by RituCs** [comment]
> Perfect! Thanks!

My pleasure.It was great experience.Thank you for your help throughout the process.Looking forward to contribute more. Thanks !

**Pull request merged**
