### PR TITLE
Get .env from .json

### LINKED ISSUE #124: A shell script to produce .env from .json file
The onboarding/setup process for a developer into the RocketMeet ecosystem can get a bit lengthy. Gotta setup firebase and then copy the vars from the .json file to .env

A shell script could help to produce .env files for each repository from .json files that we get from Firebase. 

Path to the downloaded .json files could be passed as command-line arguments or the user could be prompted for it. The .json files could later on be deleted by the script since they serve no further purpose and should not be lying around anyhow. (since they contain the keys).

### PR DESCRIPTION
**Pull request by viveknathani**
fix #124

### CODE REVIEW

**Review by BreadGenie — CHANGES_REQUESTED** [review]
The newline seems to be not properly appended in .env files.
```
TYPE=service_account\nPROJECT_ID=rocketmeet-xxxxx\nPRIVATE_KEY_ID=xxxxxxxxxxxxxxxxxxxde7e301ef\nPRIVATE_KEY=-----BEGIN\nPRIVATE=KEY----
``` 
is how I got the env file. We need the `\n` to appear as a newline
try using `echo $output >> .env` in every loop.

**Comment by BreadGenie** [comment]
Took a look and noticed

**Comment by BreadGenie** [comment]
That was an accident :D 
You could specify " closes #126 " or something related while creating a PR to link the PR with the respective issue.
[GitHub Docs ](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)on the same

**Comment by viveknathani** [comment]
> 
> 
> The newline seems to be not properly appended in .env files.
> 
> ```
> TYPE=service_account\nPROJECT_ID=rocketmeet-xxxxx\nPRIVATE_KEY_ID=xxxxxxxxxxxxxxxxxxxde7e301ef\nPRIVATE_KEY=-----BEGIN\nPRIVATE=KEY----
> ```
> 
> is how I got the env file. We need the `\n` to appear as a newline
> try using `echo $output >> .env` in every loop.

all right, I made the changes.

**Comment by BreadGenie** [comment]
Everything except `PRIVATE_KEY` looks fine.

This is the .env file produced
```
PRIVATE=KEY-----\nPJjuV7bi1l2HDy9NdTWLD7MyuWITyDTwooYM8KYhYS7VFwlGqJnc4z+BlUOM\nZAPbJY5HB9+6tQ9vVeOlWdrRYk5Q3ItSgYsaMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD1xNK66CJnWjGL\nJ6Cup01CamFqs9x7vc+mxAPfr5VmTEcvfTX0nm4u1eCgUpkJeTePTFkXiMJvbMZF\nso73eL7W+klSa9OGRaxO/DQ3TR9DR724dhCBMORJXNNt9+Gu/GUTDP/uJoLvqatV\nyaT+goZTQjJX47MsatmvMsqXV5Sjq3FgPaWxCZe3u6jJg8VykdEZRUkU87pNGRF0\nbWvlSb7lQSM5QASc5os4Fk2oMRJAJ5oh3n2R62cm+A4GUa1KPPgfPXSenUbxK2qc\nUwBAcChc3Jv+hLHt7tJB5+Knr1nXn7WoQ1seSuZ+M4pmTJg5x2ELEVeORhc2BY5q\nJPXwBR6pAgMBAAECggEAFRU7VplPSjpsgZl2qUTk1cu2a6beRSc1RwMNqgSv9kSY\n3rQJCuEEZrQmPtqXEj75yysrgV9T/qcAIz58ETKkfGCgJZfmX2Beta/g8tWE1wqy\ndb57D/oXu0thP8/B5nb0XLwCwHVBSjnt3sAbjVG5IC9PjkaUOj04S1U6F92FfLyv\nRSUQ/ZY5Z0RPGQ9nqOlhg3e/NOV8u3blZHIyrbN7lE+3soKkhx/HtMF0006bMbQX\nnMnroqAwLQnUonUF/5dD3g5NqsWexC6EIBWXuCwJrwBbHBQC2j5MhHFVpR/2nRq8\nEfUpXmpW4swvH+77XBSxr8MVxNBVEMxqRbQ6Z4Ii4QKBgQD+N2E3TyJEZqgIoUFQ\nIkE90lHRauvLY5D0d5FBpsVWnlQ/AoQvVZom4MmOYJmgfcm+xiYdtnwVZdvSCg7h\nGNMuzsmsQ9KiwtkxESlcCAqvvf2agVMQ8uE/is0hu+FGUFoAw2WAUj83hLiAyOX6\nG9R+/uxiY9ulvc4rkJUwT5B6RQKBgQD3fkUoC8lRbWmrwIHPjOumRbWw080HAK47\nnhLwHErTznJMXUg7cF2JmNBIgASKXxq9\nu6rn+POrFQKBgQCmy79Fgu6A4rotr2AjK9aSsYRtWzIK6PEa9big0sN36bps/UkA061Crln\nY5vjLWg72v1UaNZkmXMk3CCvaeSNJhHHYGITlXzoY1M6u6AhB3fqIZ5Z2QXMa+Hg\n6LssqktmB/3Y9AQQ7GhcymLGt\nrQTPrX2RpWAnJWFRgsFPjYQspgBs95x7pMYrWBKKrJVvpVjMEO6KK9yXIpla3q+Z\n10JjZrbhA1zzvZTQG2RlpZFE5BgKp8X9LHVoPerrQ4nCXZ8AhoTchdfN4QKBgDq9\n4qYtnfvQr0sPpv/fH7NYSlaM/tXRqIkH7NDOYTH46bSPUqWSyhRlZG78K/k3HPs7\nAq22tYBuwc+cZGQ5Un9N1y8hVNpp1h2FQ5EJKercCJMlFGPFjAGcAR6/aX0xy3Oq\nwZxR6MS69FABt/oHS11RuqZpDW7okfdWFpM4EcDabJsz5S9dwA9AoGBAMPe0Xw39ZhJNhAYnzH1\n4mn9S/d4lJeHafYUwQKTYtNqUjdaQ3rnYw8D1jTEmvbw3\n-----END
PRIVATE=KEY-----\n
```
Here at the start and end there shouldn't be `PRIVATE=KEY` it should be `PRIVATE_KEY`. Also there shouldn't be a newline in there

**Comment by viveknathani** [comment]
> 
> 
> Everything except `PRIVATE_KEY` looks fine.
> 
> This is the .env file produced
> 
> ```
> PRIVATE=KEY-----\nPJjuV7bi1l2HDy9NdTWLD7MyuWITyDTwooYM8KYhYS7VFwlGqJnc4z+BlUOM\nZAPbJY5HB9+6tQ9vVeOlWdrRYk5Q3ItSgYsaMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD1xNK66CJnWjGL\nJ6Cup01CamFqs9x7vc+mxAPfr5VmTEcvfTX0nm4u1eCgUpkJeTePTFkXiMJvbMZF\nso73eL7W+klSa9OGRaxO/DQ3TR9DR724dhCBMORJXNNt9+Gu/GUTDP/uJoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvbw3\n-----END
> PRIVATE=KEY-----\n
> ```
> 
> Here at the start and end there shouldn't be `PRIVATE=KEY` it should be `PRIVATE_KEY`. Also there shouldn't be a newline in there

I made some changes. Had to switch from `sh` to `bash` to fix the \n behavior.

**Review by BreadGenie — CHANGES_REQUESTED** [review]
`client_email` is produced in small letters instead of the usual caps.
Everything else looks good to me!

**Comment by viveknathani** [comment]
> 
> 
> `client_email` is produced in small letters instead of the usual caps.
> Everything else looks good to me!

aah yes, I made it upper case now. Please check.

**Review by BreadGenie — COMMENTED** [review]
It works perfectly now!
But I just noticed that these .env variables are required in the mailer and server repos of RocketMeet. There's only 2 variables required for client side. I should've noticed that sooner. Sorry about that. So maybe you can make PRs for server and mailer with this shell script and edit this PR to only extract those 2 variables.
Also you can maybe try to produce the .env like a template like in the example (then we may not need an example file :thinking: )
```
NEXT_PUBLIC_API_KEY=firebaseapp_api_key_from_json
NEXT_PUBLIC_AUTH_DOMAIN=firebaseapp_auth_domain_from_json

## All secret environmental variables are stored here

# Secrets

NEXT_PUBLIC_ENCRYPTION_KEY=your key of length 32 characters here
NEXT_PUBLIC_ENCRYPTION_IV=your key of length 16 characters here

## All development environmental variables are stored here
## `next dev`

# Development URLs

NEXT_PUBLIC_VERSION_NUMBER=1
NEXT_PUBLIC_SERVER_DOMAIN=http://localhost:5000
NEXT_PUBLIC_ORIGIN_DOMAIN=http://localhost:3000
NEXT_PUBLIC_MAILER_DOMAIN=http://localhost:8000
```
@AnandBaburajan what do you think?

**Comment by viveknathani** [comment]
I think we could let go the part for writing the script for the client since it is just two variables. The real pain point is in the server and the mailer. For them, we could update the README of the client itself? To point the reader to the env.sh script for setting up. Let me know what you guys think and I will make the changes after that.

**Comment by BreadGenie** [comment]
If you think there's no need for a script at client then we can close this PR and create another one at server or both server and mailer

**Comment by viveknathani** [comment]
Sounds cool, here is a suggestion of the steps we should take:
close the PR here
open a PR at server, add the script over there and update its README 
open a PR at mailer, just to update the README which would contain something like "use the env.sh file from mailer"

**Comment by viveknathani** [comment]
@BreadGenie should I go ahead with the steps?

**Comment by BreadGenie** [comment]
Sure! Go ahead.

**Pull request closed without merging**
